# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfz6FlnIau5xPIILRKjUOomMKbMDzPu1

practicing or testing snippets of code
"""

from math import pi
import random


def routine(num1, num2):
    bartok = ((((num1 * num2) + (num1 / num2)) - num2 + num1) / num1)
    return bartok


num1 = int(input("input first number"))
num2 = int(input("enter second number:"))
#
# output numbers with routine resunlts and two different randoms.
output = routine(num1, num2)

out2 = 100 * random.random()
out3 = random.randint(1, 100)
#
# formated output text with rounding
print(f"Result will be:\n input 1 ", num1, "and input 2 ", num2, "=",
      output, "\nand always pi; ", pi, "\n",    round(out2),     out3)

"""add some more text from menu bar."""
